# Generated by Django 6.0.3 on 2026-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('fullstack', 'Fullstack')], default='web', max_length=20)),
                ('deployed', models.BooleanField(default=False)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='web', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('category', models.CharField(choices=[('languages', 'Langages'), ('frameworks', 'Frameworks / Outils')], max_length=20)),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
    ]
