# Generated by Django 6.0.1 on 2026-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('snake', 'Snake'), ('quiz', 'Quiz Ivoirien')], max_length=10)),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('correct', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', 'duration'],
            },
        ),
    ]
